#include "GFaceToolsUI.h"

using namespace XE;
bool GFaceToolsUI::createUI()
{
	m_isShowFeatureDataChk.initWithoutSkin("是否显示特征点");
	m_isShowFeatureDataChk.setPosition(5,485);
	m_isShowFeatureDataChk.setScale(1,1);
	m_dataResourcesTypeCmb.initWithoutSkin(128,2,2);
	m_dataResourcesTypeCmb.setPosition(275,484);
	m_dataResourcesTypeCmb.setScale(1,1);
	m_dataResourcesTypeCmb.setMenuStr("摄像头;视频文件;");
	m_startOrStopBtn.initWithoutSkin("开始",XVec2(128,32));
	m_startOrStopBtn.setPosition(438,484);
	m_startOrStopBtn.setScale(1,1);
	m_chooseFileBtn.initWithoutSkin("选择文件",XVec2(128,32));
	m_chooseFileBtn.setPosition(5,520);
	m_chooseFileBtn.setScale(1,1);
	m_curFilenameTxt.init("F:/xiajia.avi");
	m_curFilenameTxt.setPosition(138,520);
	m_curFilenameTxt.setScale(1,1);
	m_camIndexTxt.init("编号:");
	m_camIndexTxt.setPosition(5,554);
	m_camIndexTxt.setScale(1,1);
	m_camIndexEdt.initWithoutSkin(XVec2(32,32),"0");
	m_camIndexEdt.setPosition(82,554);
	m_camIndexEdt.setScale(1,1);
	m_camWidthTxt.init("宽:");
	m_camWidthTxt.setPosition(117,554);
	m_camWidthTxt.setScale(1,1);
	m_camWidthEdt.initWithoutSkin(XVec2(70,32),"1024");
	m_camWidthEdt.setPosition(164,554);
	m_camWidthEdt.setScale(1,1);
	m_camHeightTxt.init("高:");
	m_camHeightTxt.setPosition(236,554);
	m_camHeightTxt.setScale(1,1);
	m_camHeightEdt.initWithoutSkin(XVec2(70,32),"768");
	m_camHeightEdt.setPosition(282,554);
	m_camHeightEdt.setScale(1,1);
	m_isShowCurDataChk.initWithoutSkin("是否实时显示");
	m_isShowCurDataChk.setPosition(355,554);
	m_isShowCurDataChk.setScale(1,1);
	m_basicInfoMTxt.initWithoutSkin(XVec2(1014,144),"基本信息:");
	m_basicInfoMTxt.setPosition(5,588);
	m_basicInfoMTxt.setScale(1,1);
	m_auInfoMTxt.initWithoutSkin(XVec2(185,480),"AU信息:");
	m_auInfoMTxt.setPosition(646,2);
	m_auInfoMTxt.setScale(1,1);
	m_suInfoMTxt.initWithoutSkin(XVec2(185,480),"SU信息:");
	m_suInfoMTxt.setPosition(834,2);
	m_suInfoMTxt.setScale(1,1);
	m_oscSenderIPTxt.init("IP:");
	m_oscSenderIPTxt.setPosition(576,484);
	m_oscSenderIPTxt.setScale(1,1);
	m_oscSenderIPEdt.initWithoutSkin(XVec2(256,32),"127.0.0.1");
	m_oscSenderIPEdt.setPosition(622,485);
	m_oscSenderIPEdt.setScale(1,1);
	m_oscSenderIPEdt.setComment("Osc通讯的IP地址");
	m_oscSenderPortTxt.init("发送端口:");
	m_oscSenderPortTxt.setPosition(577,520);
	m_oscSenderPortTxt.setScale(1,1);
	m_oscSenderPortEdt.initWithoutSkin(XVec2(164,32),"12345");
	m_oscSenderPortEdt.setPosition(714,519);
	m_oscSenderPortEdt.setScale(1,1);
	m_oscRecvPortTxt.init("接收端口:");
	m_oscRecvPortTxt.setPosition(576,554);
	m_oscRecvPortTxt.setScale(1,1);
	m_oscRecvPortEdt.initWithoutSkin(XVec2(164,32),"54321");
	m_oscRecvPortEdt.setPosition(714,554);
	m_oscRecvPortEdt.setScale(1,1);
	return true;
}
bool GFaceToolsUI::disableAll()
{
	m_isShowFeatureDataChk.disable();
	m_dataResourcesTypeCmb.disable();
	m_startOrStopBtn.disable();
	m_chooseFileBtn.disable();
	m_camIndexEdt.disable();
	m_camWidthEdt.disable();
	m_camHeightEdt.disable();
	m_isShowCurDataChk.disable();
	m_basicInfoMTxt.disable();
	m_auInfoMTxt.disable();
	m_suInfoMTxt.disable();
	m_oscSenderIPEdt.disable();
	m_oscSenderPortEdt.disable();
	m_oscRecvPortEdt.disable();
	return true;
}
bool GFaceToolsUI::enableAll()
{
	m_isShowFeatureDataChk.enable();
	m_dataResourcesTypeCmb.enable();
	m_startOrStopBtn.enable();
	m_chooseFileBtn.enable();
	m_camIndexEdt.enable();
	m_camWidthEdt.enable();
	m_camHeightEdt.enable();
	m_isShowCurDataChk.enable();
	m_basicInfoMTxt.enable();
	m_auInfoMTxt.enable();
	m_suInfoMTxt.enable();
	m_oscSenderIPEdt.enable();
	m_oscSenderPortEdt.enable();
	m_oscRecvPortEdt.enable();
	return true;
}
bool GFaceToolsUI::visibleAll()
{
	m_isShowFeatureDataChk.setVisible();
	m_dataResourcesTypeCmb.setVisible();
	m_startOrStopBtn.setVisible();
	m_chooseFileBtn.setVisible();
	m_curFilenameTxt.setVisible();
	m_camIndexTxt.setVisible();
	m_camIndexEdt.setVisible();
	m_camWidthTxt.setVisible();
	m_camWidthEdt.setVisible();
	m_camHeightTxt.setVisible();
	m_camHeightEdt.setVisible();
	m_isShowCurDataChk.setVisible();
	m_basicInfoMTxt.setVisible();
	m_auInfoMTxt.setVisible();
	m_suInfoMTxt.setVisible();
	m_oscSenderIPTxt.setVisible();
	m_oscSenderIPEdt.setVisible();
	m_oscSenderPortTxt.setVisible();
	m_oscSenderPortEdt.setVisible();
	m_oscRecvPortTxt.setVisible();
	m_oscRecvPortEdt.setVisible();
	return true;
}
bool GFaceToolsUI::hideAll()
{
	m_isShowFeatureDataChk.disVisible();
	m_dataResourcesTypeCmb.disVisible();
	m_startOrStopBtn.disVisible();
	m_chooseFileBtn.disVisible();
	m_curFilenameTxt.disVisible();
	m_camIndexTxt.disVisible();
	m_camIndexEdt.disVisible();
	m_camWidthTxt.disVisible();
	m_camWidthEdt.disVisible();
	m_camHeightTxt.disVisible();
	m_camHeightEdt.disVisible();
	m_isShowCurDataChk.disVisible();
	m_basicInfoMTxt.disVisible();
	m_auInfoMTxt.disVisible();
	m_suInfoMTxt.disVisible();
	m_oscSenderIPTxt.disVisible();
	m_oscSenderIPEdt.disVisible();
	m_oscSenderPortTxt.disVisible();
	m_oscSenderPortEdt.disVisible();
	m_oscRecvPortTxt.disVisible();
	m_oscRecvPortEdt.disVisible();
	return true;
}
